// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.6.1
// source: protobuf/comment.proto

package commentpb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Comment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     uint64                 `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PostId        uint64                 `protobuf:"varint,3,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	ReplyTo       uint64                 `protobuf:"varint,4,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Likes         uint32                 `protobuf:"varint,6,opt,name=likes,proto3" json:"likes,omitempty"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_protobuf_comment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_comment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_protobuf_comment_proto_rawDescGZIP(), []int{0}
}

func (x *Comment) GetCommentId() uint64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *Comment) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Comment) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *Comment) GetReplyTo() uint64 {
	if x != nil {
		return x.ReplyTo
	}
	return 0
}

func (x *Comment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Comment) GetLikes() uint32 {
	if x != nil {
		return x.Likes
	}
	return 0
}

func (x *Comment) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type AddCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PostId        uint64                 `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCommentRequest) Reset() {
	*x = AddCommentRequest{}
	mi := &file_protobuf_comment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommentRequest) ProtoMessage() {}

func (x *AddCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_comment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommentRequest.ProtoReflect.Descriptor instead.
func (*AddCommentRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_comment_proto_rawDescGZIP(), []int{1}
}

func (x *AddCommentRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddCommentRequest) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *AddCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type AddCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	CommentId     uint64                 `protobuf:"varint,2,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCommentResponse) Reset() {
	*x = AddCommentResponse{}
	mi := &file_protobuf_comment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommentResponse) ProtoMessage() {}

func (x *AddCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_comment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommentResponse.ProtoReflect.Descriptor instead.
func (*AddCommentResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_comment_proto_rawDescGZIP(), []int{2}
}

func (x *AddCommentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddCommentResponse) GetCommentId() uint64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

type GetCommentsReqeust struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentsReqeust) Reset() {
	*x = GetCommentsReqeust{}
	mi := &file_protobuf_comment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentsReqeust) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentsReqeust) ProtoMessage() {}

func (x *GetCommentsReqeust) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_comment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentsReqeust.ProtoReflect.Descriptor instead.
func (*GetCommentsReqeust) Descriptor() ([]byte, []int) {
	return file_protobuf_comment_proto_rawDescGZIP(), []int{3}
}

func (x *GetCommentsReqeust) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type GetCommentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*Comment             `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentsResponse) Reset() {
	*x = GetCommentsResponse{}
	mi := &file_protobuf_comment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentsResponse) ProtoMessage() {}

func (x *GetCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_comment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentsResponse.ProtoReflect.Descriptor instead.
func (*GetCommentsResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_comment_proto_rawDescGZIP(), []int{4}
}

func (x *GetCommentsResponse) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

var File_protobuf_comment_proto protoreflect.FileDescriptor

const file_protobuf_comment_proto_rawDesc = "" +
	"\n" +
	"\x16protobuf/comment.proto\x12\x04post\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe0\x01\n" +
	"\aComment\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\x04R\tcommentId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x17\n" +
	"\apost_id\x18\x03 \x01(\x04R\x06postId\x12\x19\n" +
	"\breply_to\x18\x04 \x01(\x04R\areplyTo\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x14\n" +
	"\x05likes\x18\x06 \x01(\rR\x05likes\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"_\n" +
	"\x11AddCommentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\x04R\x06postId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"M\n" +
	"\x12AddCommentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x02 \x01(\x04R\tcommentId\"-\n" +
	"\x12GetCommentsReqeust\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x04R\x06postId\"@\n" +
	"\x13GetCommentsResponse\x12)\n" +
	"\bcomments\x18\x01 \x03(\v2\r.post.CommentR\bcomments2\x95\x01\n" +
	"\x0eCommentService\x12?\n" +
	"\n" +
	"AddComment\x12\x17.post.AddCommentRequest\x1a\x18.post.AddCommentResponse\x12B\n" +
	"\vGetComments\x12\x18.post.GetCommentsReqeust\x1a\x19.post.GetCommentsResponseB\x1dZ\x1brpc_gen/commentpb;commentpbb\x06proto3"

var (
	file_protobuf_comment_proto_rawDescOnce sync.Once
	file_protobuf_comment_proto_rawDescData []byte
)

func file_protobuf_comment_proto_rawDescGZIP() []byte {
	file_protobuf_comment_proto_rawDescOnce.Do(func() {
		file_protobuf_comment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_comment_proto_rawDesc), len(file_protobuf_comment_proto_rawDesc)))
	})
	return file_protobuf_comment_proto_rawDescData
}

var file_protobuf_comment_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protobuf_comment_proto_goTypes = []any{
	(*Comment)(nil),             // 0: post.Comment
	(*AddCommentRequest)(nil),   // 1: post.AddCommentRequest
	(*AddCommentResponse)(nil),  // 2: post.AddCommentResponse
	(*GetCommentsReqeust)(nil),  // 3: post.GetCommentsReqeust
	(*GetCommentsResponse)(nil), // 4: post.GetCommentsResponse
	(*timestamp.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_protobuf_comment_proto_depIdxs = []int32{
	5, // 0: post.Comment.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: post.GetCommentsResponse.comments:type_name -> post.Comment
	1, // 2: post.CommentService.AddComment:input_type -> post.AddCommentRequest
	3, // 3: post.CommentService.GetComments:input_type -> post.GetCommentsReqeust
	2, // 4: post.CommentService.AddComment:output_type -> post.AddCommentResponse
	4, // 5: post.CommentService.GetComments:output_type -> post.GetCommentsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protobuf_comment_proto_init() }
func file_protobuf_comment_proto_init() {
	if File_protobuf_comment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_comment_proto_rawDesc), len(file_protobuf_comment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_comment_proto_goTypes,
		DependencyIndexes: file_protobuf_comment_proto_depIdxs,
		MessageInfos:      file_protobuf_comment_proto_msgTypes,
	}.Build()
	File_protobuf_comment_proto = out.File
	file_protobuf_comment_proto_goTypes = nil
	file_protobuf_comment_proto_depIdxs = nil
}
