// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.6.1
// source: protobuf/rec.proto

package recpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TopicId       uint64                 `protobuf:"varint,2,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	Size          uint64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecRequest) Reset() {
	*x = RecRequest{}
	mi := &file_protobuf_rec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecRequest) ProtoMessage() {}

func (x *RecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_rec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecRequest.ProtoReflect.Descriptor instead.
func (*RecRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_rec_proto_rawDescGZIP(), []int{0}
}

func (x *RecRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RecRequest) GetTopicId() uint64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *RecRequest) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type RecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostIdList    []uint64               `protobuf:"varint,1,rep,packed,name=post_id_list,json=postIdList,proto3" json:"post_id_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecResponse) Reset() {
	*x = RecResponse{}
	mi := &file_protobuf_rec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecResponse) ProtoMessage() {}

func (x *RecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_rec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecResponse.ProtoReflect.Descriptor instead.
func (*RecResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_rec_proto_rawDescGZIP(), []int{1}
}

func (x *RecResponse) GetPostIdList() []uint64 {
	if x != nil {
		return x.PostIdList
	}
	return nil
}

var File_protobuf_rec_proto protoreflect.FileDescriptor

const file_protobuf_rec_proto_rawDesc = "" +
	"\n" +
	"\x12protobuf/rec.proto\x12\x03rec\"T\n" +
	"\n" +
	"RecRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x19\n" +
	"\btopic_id\x18\x02 \x01(\x04R\atopicId\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\"/\n" +
	"\vRecResponse\x12 \n" +
	"\fpost_id_list\x18\x01 \x03(\x04R\n" +
	"postIdList2;\n" +
	"\n" +
	"RecService\x12-\n" +
	"\bRecPosts\x12\x0f.rec.RecRequest\x1a\x10.rec.RecResponseB\x15Z\x13rpc_gen/recpb;recpbb\x06proto3"

var (
	file_protobuf_rec_proto_rawDescOnce sync.Once
	file_protobuf_rec_proto_rawDescData []byte
)

func file_protobuf_rec_proto_rawDescGZIP() []byte {
	file_protobuf_rec_proto_rawDescOnce.Do(func() {
		file_protobuf_rec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_rec_proto_rawDesc), len(file_protobuf_rec_proto_rawDesc)))
	})
	return file_protobuf_rec_proto_rawDescData
}

var file_protobuf_rec_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_rec_proto_goTypes = []any{
	(*RecRequest)(nil),  // 0: rec.RecRequest
	(*RecResponse)(nil), // 1: rec.RecResponse
}
var file_protobuf_rec_proto_depIdxs = []int32{
	0, // 0: rec.RecService.RecPosts:input_type -> rec.RecRequest
	1, // 1: rec.RecService.RecPosts:output_type -> rec.RecResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_rec_proto_init() }
func file_protobuf_rec_proto_init() {
	if File_protobuf_rec_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_rec_proto_rawDesc), len(file_protobuf_rec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_rec_proto_goTypes,
		DependencyIndexes: file_protobuf_rec_proto_depIdxs,
		MessageInfos:      file_protobuf_rec_proto_msgTypes,
	}.Build()
	File_protobuf_rec_proto = out.File
	file_protobuf_rec_proto_goTypes = nil
	file_protobuf_rec_proto_depIdxs = nil
}
