// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.6.1
// source: protobuf/rec.proto

package recpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RecService_RecPosts_FullMethodName = "/rec.RecService/RecPosts"
)

// RecServiceClient is the client API for RecService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecServiceClient interface {
	RecPosts(ctx context.Context, in *RecRequest, opts ...grpc.CallOption) (*RecResponse, error)
}

type recServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRecServiceClient(cc grpc.ClientConnInterface) RecServiceClient {
	return &recServiceClient{cc}
}

func (c *recServiceClient) RecPosts(ctx context.Context, in *RecRequest, opts ...grpc.CallOption) (*RecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecResponse)
	err := c.cc.Invoke(ctx, RecService_RecPosts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecServiceServer is the server API for RecService service.
// All implementations must embed UnimplementedRecServiceServer
// for forward compatibility.
type RecServiceServer interface {
	RecPosts(context.Context, *RecRequest) (*RecResponse, error)
	mustEmbedUnimplementedRecServiceServer()
}

// UnimplementedRecServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecServiceServer struct{}

func (UnimplementedRecServiceServer) RecPosts(context.Context, *RecRequest) (*RecResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecPosts not implemented")
}
func (UnimplementedRecServiceServer) mustEmbedUnimplementedRecServiceServer() {}
func (UnimplementedRecServiceServer) testEmbeddedByValue()                    {}

// UnsafeRecServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecServiceServer will
// result in compilation errors.
type UnsafeRecServiceServer interface {
	mustEmbedUnimplementedRecServiceServer()
}

func RegisterRecServiceServer(s grpc.ServiceRegistrar, srv RecServiceServer) {
	// If the following call pancis, it indicates UnimplementedRecServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RecService_ServiceDesc, srv)
}

func _RecService_RecPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecServiceServer).RecPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecService_RecPosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecServiceServer).RecPosts(ctx, req.(*RecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RecService_ServiceDesc is the grpc.ServiceDesc for RecService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rec.RecService",
	HandlerType: (*RecServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecPosts",
			Handler:    _RecService_RecPosts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/rec.proto",
}
